apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secrets
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.env.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  mysql-user-password: {{ .Values.mysql.env.MYSQL_PASSWORD | b64enc | quote }}
  redis-password: {{ .Values.redis.env.REDIS_PASSWORD | b64enc | quote }}
  php-app-key: {{ .Values.php.env.APP_KEY | b64enc | quote }}
  php-db-password: {{ .Values.php.env.DB_PASSWORD | b64enc | quote }}