apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-mysql
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: {{ include "myapp.fullname" . }}-mysql
