apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-php
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.php.replicas }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-php
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-php
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z myapp-mysql 3306; do echo "Waiting for MySQL"; sleep 2; done;']
      containers:
      - name: php
        image: "{{ .Values.php.image }}"
        ports:
        - containerPort: {{ .Values.php.ports.containerPort }}
        resources:
          requests:
            cpu: "{{ .Values.php.cpu }}"
            memory: "{{ .Values.php.memory }}"
        readinessProbe:
          exec:
            command:
              - curl
              - http://localhost
          periodSeconds: 10
          timeoutSeconds: 10
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "myapp.fullname" . }}-secrets
              key: php-app-key
        - name: APP_ENV
          value: "{{ .Values.php.env.APP_ENV }}"
        - name: APP_DEBUG
          value: "{{ .Values.php.env.APP_DEBUG }}"
        - name: DB_PORT
          value: "{{ .Values.php.env.DB_PORT }}"
        - name: DB_HOST
          value: "{{ .Values.php.env.DB_HOST }}"
        - name: DB_DATABASE
          value: "{{ .Values.php.env.DB_DATABASE }}"
        - name: DB_USERNAME
          value: "{{ .Values.php.env.DB_USERNAME }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "myapp.fullname" . }}-secrets
              key: php-db-password
        - name: REDIS_HOST
          value: "{{ .Values.php.env.REDIS_HOST }}"
        - name: REDIS_PORT
          value: "{{ .Values.php.env.REDIS_PORT }}"
        - name: REDIS_USERNAME
          value: "{{ .Values.php.env.REDIS_USERNAME }}"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "myapp.fullname" . }}-secrets
              key: redis-password
        
