apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-redis
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image }}"
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "myapp.fullname" . }}-secrets
              key: redis-password
        - name: REDIS_PORT
          value: "{{ .Values.redis.env.REDIS_PORT }}"
        - name: REDIS_USERNAME
          value: "{{ .Values.redis.env.REDIS_USERNAME }}"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
